# -*- coding: utf-8 -*-
"""SmartCase VN Toàn Diện

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RcwGtuNjYCUYXBFHDZAKDZQrC5EaL91H
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime, timedelta
import json
import requests
import time
import base64

# ==========================================
# 1. CẤU HÌNH TRANG & GIAO DIỆN (CSS)
# ==========================================
st.set_page_config(page_title="SmartCase VN - Quản lý Ca AI", page_icon="🛡️", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
    <style>
    /* Tổng thể UI */
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }

    /* Làm đẹp các Metric (Chỉ số) */
    [data-testid="stMetric"] {
        background-color: #ffffff;
        border: 1px solid #e2e8f0;
        padding: 15px 20px;
        border-radius: 12px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }

    /* Làm đẹp thẻ Container (Card) */
    [data-testid="stVerticalBlockBorderWrapper"] {
        border-radius: 16px;
        border-color: #e2e8f0;
        background-color: #ffffff;
        box-shadow: 0 2px 4px rgba(0,0,0,0.02);
        transition: all 0.2s ease;
    }
    [data-testid="stVerticalBlockBorderWrapper"]:hover {
        border-color: #cbd5e1;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
    }

    /* Style cho các nút bấm */
    .stButton>button {
        border-radius: 8px;
        font-weight: 600;
    }

    /* Badge Trạng thái custom */
    .badge {
        padding: 4px 12px;
        border-radius: 99px;
        font-size: 13px;
        font-weight: bold;
        display: inline-flex;
        align-items: center;
        gap: 6px;
    }
    .badge-red { background-color: #fee2e2; color: #b91c1c; }
    .badge-yellow { background-color: #fef9c3; color: #b45309; }
    .badge-green { background-color: #dcfce7; color: #15803d; }
    .badge-blue { background-color: #dbeafe; color: #1d4ed8; }
    .badge-gray { background-color: #f1f5f9; color: #475569; }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. HÀM HỖ TRỢ (DATE, API, IMAGE)
# ==========================================
def format_date_vn(date_obj):
    return date_obj.strftime("%d/%m/%Y")

def parse_date_vn(date_str):
    try: return datetime.strptime(date_str, "%d/%m/%Y")
    except: return datetime.now()

def get_base64_image(file):
    if file: return f"data:image/png;base64,{base64.b64encode(file.getvalue()).decode()}"
    return None

def call_gemini_api(prompt):
    api_key = "" # API Key provided by runtime
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key={api_key}"
    headers = {'Content-Type': 'application/json'}
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"responseMimeType": "application/json"}
    }
    for delay in [1, 2, 4, 8]:
        try:
            res = requests.post(url, headers=headers, json=payload)
            if res.status_code == 200:
                return res.json()['candidates'][0]['content']['parts'][0]['text']
        except:
            time.sleep(delay)
    return "{}"

# ==========================================
# 3. KHỞI TẠO DỮ LIỆU (SESSION STATE)
# ==========================================
def init_mock_data():
    today = datetime.now()
    add_days = lambda d: format_date_vn(today + timedelta(days=d))

    return [
        {
            "id": "TE-001", "alias": "L.T.H", "age": 16, "category": "Bạo lực gia đình",
            "riskLevel": "Khẩn cấp", "status": "Đang can thiệp", "avatar": None,
            "address": "Quận 4, TP.HCM", "phone": "090xxxxxxx",
            "details": {
                "family": "Sống với bà ngoại (70 tuổi, yếu). Mẹ đơn thân đi làm xa. Dượng ruột hay say xỉn bạo hành.",
                "history": "Từng nhập viện do chấn thương phần mềm năm 2025. Chưa từng điều trị tâm lý.",
                "swot": {
                    "S": ["Rất thương bà ngoại (động lực)", "Có năng khiếu vẽ", "Mong muốn tự lập"],
                    "W": ["Suy dinh dưỡng nhẹ", "Tâm lý lo âu, thu mình", "Kỹ năng đối phó kém"],
                    "O": ["Chính quyền địa phương đang quan tâm", "Có lớp học nghề miễn phí gần nhà"],
                    "T": ["Dượng ruột tiếp tục đe dọa bạo hành", "Nguy cơ bị lôi kéo vào tệ nạn do bỏ học"]
                },
                "goals": [
                    {
                        "id": 1, "text": "Kiểm soát hoảng loạn tâm lý (Demo Lên/Xuống)", "status": "Đang tiến hành", "deadline": add_days(10),
                        "kpi": { "baseline": 8, "current": 3, "target": 1, "unit": "Cơn/Tuần",
                                "history": [ {"date": add_days(-20), "value": 8}, {"date": add_days(-15), "value": 5}, {"date": add_days(-10), "value": 6}, {"date": add_days(-2), "value": 3} ] }
                    },
                    {
                        "id": 2, "text": "Tham vấn trị liệu tâm lý", "status": "Đang tiến hành", "deadline": add_days(2),
                        "kpi": { "baseline": 0, "current": 3, "target": 5, "unit": "Buổi",
                                "history": [ {"date": add_days(-15), "value": 0}, {"date": add_days(-10), "value": 1}, {"date": add_days(-5), "value": 2}, {"date": add_days(-2), "value": 3} ] }
                    },
                    {
                        "id": 3, "text": "Hỗ trợ quay lại trường hoặc học nghề", "status": "Chưa bắt đầu", "deadline": add_days(30),
                        "kpi": { "baseline": 0, "current": 0, "target": 100, "unit": "% Hồ sơ", "history": [{"date": add_days(0), "value": 0}] }
                    }
                ],
                "referrals": [
                    {"org": "Hội LHPN Quận 4", "service": "Hỗ trợ pháp lý / Cách ly", "status": "Đã kết nối", "date": add_days(-7)},
                    {"org": "Phòng khám Tâm lý NVH Thanh Niên", "service": "Tham vấn trị liệu", "status": "Đang điều trị", "date": add_days(-5)}
                ],
                "timeline": [
                    {"date": add_days(-2), "event": "Lượng giá: Thân chủ có tiến bộ trong việc kiểm soát hoảng loạn (giảm còn 3 cơn/tuần)."},
                    {"date": add_days(-10), "event": "Dượng ruột đến tìm. Thân chủ bị hoảng loạn nhẹ (tái phát 6 cơn/tuần). Đã kết nối Hội phụ nữ."},
                    {"date": add_days(-20), "event": "Tiếp nhận ca khẩn cấp. Phối hợp công an phường đưa thân chủ rời khỏi nhà dượng."}
                ]
            }
        },
        {
            "id": "PN-042", "alias": "T.T.B", "age": 35, "category": "Mẹ đơn thân/Nghèo",
            "riskLevel": "Trung bình", "status": "Theo dõi", "avatar": None,
            "address": "Quận 8, TP.HCM", "phone": "098xxxxxxx",
            "details": {
                "family": "Nuôi 2 con nhỏ. Chồng ly hôn không cấp dưỡng.", "history": "Khỏe mạnh.",
                "swot": {"S": ["Chăm chỉ", "Thương con"], "W": ["Học vấn thấp"], "O": ["Vay vốn CSXH"], "T": ["Kinh tế bấp bênh"]},
                "goals": [{"id": 4, "text": "Tăng thu nhập (Báo đỏ quá hạn)", "status": "Đang tiến hành", "deadline": add_days(-1), "kpi": {"baseline": 3, "current": 4, "target": 6, "unit": "Triệu", "history": [{"date": add_days(-30), "value": 3}, {"date": add_days(-10), "value": 4}]}}],
                "referrals": [], "timeline": []
            }
        },
        {
            "id": "NC-105", "alias": "L.V.C", "age": 68, "category": "Người già neo đơn",
            "riskLevel": "Thấp", "status": "Sắp đóng ca", "avatar": None,
            "address": "Bình Thạnh, TP.HCM", "phone": "Không có",
            "details": {
                "family": "Sống một mình, vợ mất, con ở xa.", "history": "Cao huyết áp, tiểu đường.",
                "swot": {"S": ["Tự lo sinh hoạt"], "W": ["Sức khỏe yếu"], "O": ["Hàng xóm hỗ trợ"], "T": ["Cô đơn"]},
                "goals": [], "referrals": [], "timeline": []
            }
        },
        {
            "id": "PN-099", "alias": "N.T.M", "age": 42, "category": "Hỗ trợ việc làm",
            "riskLevel": "Thấp", "status": "Đã đóng ca", "avatar": None,
            "address": "Quận 1, TP.HCM", "phone": "091xxxxxxx",
            "details": {
                "family": "Mẹ đơn thân. Đã ổn định.", "history": "Thất nghiệp.",
                "swot": {"S": ["Có việc làm", "Tự chủ tài chính"], "W": [], "O": [], "T": []},
                "goals": [{"id": 5, "text": "Tìm việc làm", "status": "Hoàn thành", "deadline": add_days(-60), "kpi": {"baseline": 0, "current": 1, "target": 1, "unit": "Việc", "history": [{"date": add_days(-90), "value": 0}, {"date": add_days(-60), "value": 1}]}}],
                "referrals": [], "timeline": [{"date": add_days(-60), "event": "Đạt mục tiêu. Đóng ca."}]
            }
        }
    ]

if 'clients' not in st.session_state:
    st.session_state.clients = init_mock_data()
if 'current_page' not in st.session_state:
    st.session_state.current_page = "Dashboard"
if 'selected_client_id' not in st.session_state:
    st.session_state.selected_client_id = None

# ==========================================
# 4. HỆ THỐNG HỘP THOẠI (MODALS)
# ==========================================
@st.dialog("⚠️ Xác nhận Xóa")
def delete_client_dialog(client_id):
    st.write(f"Bạn có chắc chắn muốn xóa vĩnh viễn hồ sơ **{client_id}**?")
    st.error("Toàn bộ dữ liệu sẽ bị xóa bỏ hoàn toàn. Hành động này không thể hoàn tác!")
    col1, col2 = st.columns(2)
    if col1.button("Hủy bỏ", use_container_width=True):
        st.rerun()
    if col2.button("Đồng ý Xóa", type="primary", use_container_width=True):
        st.session_state.clients = [c for c in st.session_state.clients if c['id'] != client_id]
        if st.session_state.selected_client_id == client_id:
            st.session_state.selected_client_id = None
            st.session_state.current_page = "Clients"
        st.rerun()

@st.dialog("✅ Đóng Ca Hồ Sơ")
def close_case_dialog(client_id):
    st.write("Bạn có chắc chắn muốn kết thúc can thiệp và đóng ca này?")
    st.info("Hồ sơ sẽ được chuyển vào Kho lưu trữ 'Đã đóng ca'.")
    if st.button("Xác nhận Đóng Ca", type="primary", use_container_width=True):
        for c in st.session_state.clients:
            if c['id'] == client_id:
                c['status'] = "Đã đóng ca"
                c['details']['timeline'].insert(0, {"date": format_date_vn(datetime.now()), "event": "Tiến hành lượng giá cuối kỳ. Đóng ca."})
        st.rerun()

@st.dialog("🔄 Mở Lại Hồ Sơ")
def reopen_case_dialog(client_id):
    st.write("Bạn muốn mở lại hồ sơ này để tiếp tục can thiệp?")
    if st.button("Xác nhận Mở Lại", type="primary", use_container_width=True):
        for c in st.session_state.clients:
            if c['id'] == client_id:
                c['status'] = "Đang can thiệp"
                c['details']['timeline'].insert(0, {"date": format_date_vn(datetime.now()), "event": "Hồ sơ được mở lại để can thiệp tiếp."})
        st.rerun()

# ==========================================
# 5. CÁC TRANG HIỂN THỊ (PAGES)
# ==========================================

# --- PAGE: DASHBOARD ---
def render_dashboard():
    st.header(":material/dashboard: Bảng Điều Khiển Hệ Thống")
    st.divider()

    active_cases = len([c for c in st.session_state.clients if c['status'] != 'Đã đóng ca'])
    urgent_cases = len([c for c in st.session_state.clients if c['riskLevel'] == 'Khẩn cấp' and c['status'] != 'Đã đóng ca'])

    col1, col2, col3 = st.columns(3)
    col1.metric("Tổng số ca đang quản lý", active_cases)
    col2.metric("Ca báo động Khẩn cấp", urgent_cases)
    col3.metric("Mục tiêu hoàn thành", "75%")

    st.subheader(":material/notifications_active: Chuông báo Hệ thống")
    warnings_found = False

    for client in st.session_state.clients:
        if client['status'] == 'Đã đóng ca': continue
        for goal in client['details'].get('goals', []):
            if goal['status'] == 'Hoàn thành': continue

            d_date = parse_date_vn(goal['deadline'])
            diff_days = (d_date - datetime.now()).days

            if diff_days <= 7:
                warnings_found = True
                is_overdue = diff_days < 0
                bg_color = "badge-red" if is_overdue else "badge-yellow"
                icon = "🚨" if is_overdue else "⚠️"
                text = f"Quá hạn {abs(diff_days)} ngày" if is_overdue else (f"Còn {diff_days} ngày" if diff_days > 0 else "Hết hạn hôm nay")

                with st.container(border=True):
                    w_col1, w_col2 = st.columns([4, 1])
                    with w_col1:
                        st.markdown(f"**[{client['id']}] {client['alias']}** • {client['category']}")
                        st.write(f"Mục tiêu: {goal['text']}")
                        st.markdown(f"<span class='badge {bg_color}'>{icon} {text} (Hạn: {goal['deadline']})</span>", unsafe_allow_html=True)
                    with w_col2:
                        if st.button("Cập nhật ngay", key=f"warn_btn_{goal['id']}", use_container_width=True):
                            st.session_state.selected_client_id = client['id']
                            st.session_state.current_page = "Detail"
                            st.rerun()

    if not warnings_found:
        st.success("Tuyệt vời! Không có mục tiêu nào bị quá hạn hoặc sắp hết hạn.")

# --- PAGE: CLIENT LIST ---
def render_client_list():
    st.header(":material/groups: Quản lý Hồ sơ Thân chủ")
    st.caption("Dữ liệu đã được ẩn danh hóa (Anonymized) bảo mật.")
    st.divider()

    filter_col1, filter_col2 = st.columns([3, 1])
    with filter_col1:
        status_filter = st.radio("Phân loại:", ["Đang can thiệp", "Đã đóng ca"], horizontal=True, label_visibility="collapsed")
    with filter_col2:
        if st.button(":material/add_circle: Thêm Hồ Sơ Mới", type="primary", use_container_width=True):
            st.session_state.current_page = "Intake"
            st.rerun()

    filtered_clients = [c for c in st.session_state.clients if (c['status'] == "Đã đóng ca") == (status_filter == "Đã đóng ca")]

    if not filtered_clients:
        st.info("Không có hồ sơ nào trong danh mục này.")
        return

    # Table Header (Mô phỏng bằng columns)
    th_cols = st.columns([1, 2, 3, 2, 3])
    th_cols[0].write("**Ảnh**")
    th_cols[1].write("**Mã ID**")
    th_cols[2].write("**Bí danh / Nhóm**")
    th_cols[3].write("**Mức rủi ro**")
    th_cols[4].write("**Thao tác**")
    st.markdown("<hr style='margin: 0.5rem 0;'/>", unsafe_allow_html=True)

    for client in filtered_clients:
        with st.container():
            c_cols = st.columns([1, 2, 3, 2, 3], vertical_alignment="center")
            # Cột 1: Ảnh
            with c_cols[0]:
                if client['avatar']: st.image(client['avatar'], width=40)
                else: st.markdown("<div style='width:40px;height:40px;border-radius:20px;background:#e2e8f0;display:flex;align-items:center;justify-content:center;font-weight:bold;color:#475569'>{}</div>".format(client['alias'][0]), unsafe_allow_html=True)
            # Cột 2: ID
            c_cols[1].markdown(f"**{client['id']}**<br/><small style='color:gray'>{client['status']}</small>", unsafe_allow_html=True)
            # Cột 3: Info
            c_cols[2].write(f"**{client['alias']}**\n\n{client['category']}")
            # Cột 4: Risk
            risk_class = "badge-red" if client['riskLevel'] == 'Khẩn cấp' else ("badge-yellow" if client['riskLevel'] == 'Trung bình' else "badge-green")
            c_cols[3].markdown(f"<span class='badge {risk_class}'>{client['riskLevel']}</span>", unsafe_allow_html=True)
            # Cột 5: Actions
            with c_cols[4]:
                btn_cols = st.columns([2, 1])
                btn_label = "Xem Lại" if client['status'] == "Đã đóng ca" else "Xem & Can thiệp"
                if btn_cols[0].button(btn_label, key=f"view_{client['id']}", use_container_width=True):
                    st.session_state.selected_client_id = client['id']
                    st.session_state.current_page = "Detail"
                    st.rerun()
                if btn_cols[1].button(":material/delete:", key=f"del_{client['id']}", use_container_width=True):
                    delete_client_dialog(client['id'])
        st.markdown("<hr style='margin: 0.5rem 0;'/>", unsafe_allow_html=True)

# --- PAGE: INTAKE FORM ---
def render_intake():
    st.header(":material/assignment: Phiếu Tiếp Nhận & Đánh Giá Ban Đầu")
    if st.button("⬅️ Trở về danh sách"):
        st.session_state.current_page = "Clients"
        st.rerun()
    st.divider()

    # KHU VỰC AI
    with st.expander("✨ Trợ lý AI Phân tích Báo cáo Thô & SWOT", expanded=True):
        st.info("Tải lên báo cáo điền dã hoặc dán nội dung. AI sẽ tự động ẩn danh tên thật và phân tách vào biểu mẫu SWOT bên dưới.")

        up_col1, up_col2 = st.columns([2, 1])
        uploaded_file = up_col1.file_uploader("Tải file (.txt, .docx)", type=["txt", "docx"])
        raw_text = st.text_area("Hoặc dán văn bản ghi chú vào đây:", height=100)

        if st.button(":material/smart_toy: Điền & Phân tích Tự động", type="primary"):
            text_to_process = ""
            if uploaded_file:
                text_to_process = f"[FILE: {uploaded_file.name}]\n"
                # Demo mô phỏng đọc file
                text_to_process += "Hôm nay tôi đã điền dã và gặp một bé gái tên Lê Thị Hương, 16 tuổi. Bé hiện đang sống tại Quận Gò Vấp, TP.HCM. Bỏ học do dượng bạo hành. Đang sống tạm với bà ngoại (70 tuổi) già yếu. Bé trầm cảm, thu mình nhưng rất thương bà và thích vẽ tranh."
            elif raw_text:
                text_to_process = raw_text

            if text_to_process:
                with st.spinner("AI đang xử lý ngôn ngữ tự nhiên..."):
                    prompt = f"""Đóng vai chuyên gia CTXH. Trích xuất JSON từ báo cáo sau. Ẩn danh tên thật.
                    Yêu cầu JSON fields: alias, age, category, phone, address, family, history, swot_S, swot_W, swot_O, swot_T.
                    Văn bản: "{text_to_process}"
                    """
                    result = call_gemini_api(prompt)
                    try:
                        extracted = json.loads(result)
                        # Lưu tạm vào session để điền form
                        st.session_state.temp_intake = extracted
                        st.success("Đã trích xuất thành công! Dữ liệu đã được điền vào Form.")
                    except:
                        st.error("AI không thể phân tích văn bản này. Vui lòng điền tay.")
            else:
                st.warning("Vui lòng tải file hoặc nhập văn bản.")

    st.markdown("<br/>", unsafe_allow_html=True)

    # Lấy dữ liệu tạm từ AI (nếu có)
    ti = st.session_state.get('temp_intake', {})

    # FORM NHẬP LIỆU CHÍNH
    with st.form("main_intake_form"):
        st.subheader("A. Thông Tin Cơ Bản")
        col_img, col_info1, col_info2 = st.columns([1, 2, 2])

        avatar_file = col_img.file_uploader("Ảnh chân dung", type=["jpg", "png"])

        alias = col_info1.text_input("Bí danh (Bảo mật) *", value=ti.get('alias', ''))
        age = col_info1.text_input("Độ tuổi", value=ti.get('age', ''))
        phone = col_info1.text_input("Số điện thoại", value=ti.get('phone', ''))

        category = col_info2.text_input("Nhóm vấn đề xã hội", value=ti.get('category', ''))
        address = col_info2.text_area("Khu vực/Địa chỉ", value=ti.get('address', ''), height=110)

        st.markdown("<br/>", unsafe_allow_html=True)
        st.subheader("B. Hoàn Cảnh & Lịch Sử")
        family = st.text_area("Cấu trúc gia đình & Hoàn cảnh sống", value=ti.get('family', ''))
        history = st.text_area("Lịch sử tổn thương / Bệnh lý", value=ti.get('history', ''))

        st.markdown("<br/>", unsafe_allow_html=True)
        st.subheader("C. Phân Tích SWOT")
        swot_col1, swot_col2 = st.columns(2)
        s_val = swot_col1.text_area("🟢 S - Điểm mạnh nội tại", value=ti.get('swot_S', ''), height=100)
        w_val = swot_col1.text_area("🟠 W - Điểm yếu nội tại", value=ti.get('swot_W', ''), height=100)
        o_val = swot_col2.text_area("🔵 O - Cơ hội bên ngoài", value=ti.get('swot_O', ''), height=100)
        t_val = swot_col2.text_area("🟣 T - Thách thức rủi ro", value=ti.get('swot_T', ''), height=100)

        st.markdown("<br/>", unsafe_allow_html=True)
        submit_btn = st.form_submit_button("💾 Lưu Hồ Sơ Mới", type="primary", use_container_width=True)

        if submit_btn:
            if not alias:
                st.error("Vui lòng nhập Bí danh!")
            else:
                process_list = lambda text: [x.strip() for x in str(text).split('\n') if x.strip()] if text else []
                new_id = f"KH-{datetime.now().strftime('%M%S')}"

                new_client = {
                    "id": new_id, "alias": alias, "age": age, "category": category or 'Chưa phân loại',
                    "riskLevel": "Chưa đánh giá", "status": "Tiếp nhận mới", "avatar": get_base64_image(avatar_file),
                    "address": address, "phone": phone,
                    "details": {
                        "family": family, "history": history,
                        "swot": { "S": process_list(s_val), "W": process_list(w_val), "O": process_list(o_val), "T": process_list(t_val) },
                        "goals": [], "referrals": [], "timeline": [{"date": format_date_vn(datetime.now()), "event": "Khởi tạo hồ sơ tiếp nhận."}]
                    }
                }
                st.session_state.clients.insert(0, new_client)
                if 'temp_intake' in st.session_state: del st.session_state.temp_intake

                st.success(f"Đã lưu hồ sơ {new_id} thành công!")
                time.sleep(1)
                st.session_state.current_page = "Clients"
                st.rerun()

# --- PAGE: CLIENT DETAIL ---
def render_client_detail():
    client_id = st.session_state.selected_client_id
    client = next((c for c in st.session_state.clients if c['id'] == client_id), None)

    if not client:
        st.error("Không tìm thấy hồ sơ!")
        if st.button("Quay lại"):
            st.session_state.current_page = "Clients"
            st.rerun()
        return

    # HEADER Chi tiết
    h_col1, h_col2, h_col3 = st.columns([1, 6, 2], vertical_alignment="center")
    with h_col1:
        if st.button("⬅️ Trở về"):
            st.session_state.current_page = "Clients"
            st.rerun()
    with h_col2:
        st.markdown(f"## Hồ sơ: {client['id']} - {client['alias']}")
        risk_class = "badge-red" if client['riskLevel'] == 'Khẩn cấp' else ("badge-yellow" if client['riskLevel'] == 'Trung bình' else "badge-green")
        st.markdown(f"<span class='badge {risk_class}'>Mức rủi ro: {client['riskLevel']}</span> &nbsp; <span class='badge badge-gray'>Trạng thái: {client['status']}</span>", unsafe_allow_html=True)
    with h_col3:
        if st.button("🗑️ Xóa hồ sơ này", use_container_width=True):
            delete_client_dialog(client['id'])

    st.markdown("<br/>", unsafe_allow_html=True)

    # 5 TABS CHUYÊN MÔN
    tabs = st.tabs(["📂 1. Thông tin", "⚖️ 2. Đánh giá SWOT", "🎯 3. Kế hoạch KPI", "🔗 4. Nguồn lực", "📈 5. Lượng giá"])

    # TAB 1: THÔNG TIN
    with tabs[0]:
        st.subheader("Nhân khẩu học & Hoàn cảnh")
        with st.container(border=True):
            col_img, col_info = st.columns([1, 4])
            with col_img:
                if client['avatar']: st.image(client['avatar'], use_container_width=True)
                else: st.markdown("<div style='width:100%;aspect-ratio:1;border-radius:10px;background:#e2e8f0;display:flex;align-items:center;justify-content:center;font-size:3rem;font-weight:bold;color:#475569'>{}</div>".format(client['alias'][0]), unsafe_allow_html=True)
            with col_info:
                i1, i2 = st.columns(2)
                i1.write(f"**Bí danh:** {client['alias']}")
                i1.write(f"**Độ tuổi:** {client['age']}")
                i1.write(f"**Điện thoại:** {client['phone']}")
                i2.write(f"**Nhóm:** {client['category']}")
                i2.write(f"**Khu vực:** {client['address']}")

        st.markdown("**Gia đình & Môi trường:**")
        st.info(client['details']['family'] or "Chưa có thông tin")
        st.markdown("**Lịch sử Bệnh lý/Tổn thương:**")
        st.info(client['details']['history'] or "Chưa có thông tin")

    # TAB 2: SWOT
    with tabs[1]:
        st.subheader("Phân tích Đa chiều")
        swot = client['details']['swot']

        s1, s2 = st.columns(2)
        with s1:
            st.success("**🟢 S - Điểm mạnh (Nội tại)**\n\n" + "\n".join([f"- {x}" for x in swot['S']]))
            st.info("**🔵 O - Cơ hội (Bên ngoài)**\n\n" + "\n".join([f"- {x}" for x in swot['O']]))
        with s2:
            st.warning("**🟠 W - Điểm yếu (Nội tại)**\n\n" + "\n".join([f"- {x}" for x in swot['W']]))
            st.error("**🟣 T - Thách thức (Bên ngoài)**\n\n" + "\n".join([f"- {x}" for x in swot['T']]))

    # TAB 3: PLAN & KPI
    with tabs[2]:
        header_col1, header_col2 = st.columns([3, 1])
        header_col1.subheader("Lộ trình Hỗ trợ & Theo dõi KPI")

        with st.expander(":material/add_circle: Tạo Mục tiêu KPI mới"):
            with st.form("add_goal_form"):
                g_col1, g_col2 = st.columns([3, 1])
                g_text = g_col1.text_input("Nội dung mục tiêu")
                g_date = g_col2.date_input("Hạn chót (Deadline)")

                kpi_c1, kpi_c2, kpi_c3 = st.columns(3)
                g_base = kpi_c1.number_input("Chỉ số Gốc (Baseline)", value=0)
                g_target = kpi_c2.number_input("Chỉ số Đích (Target)", value=10)
                g_unit = kpi_c3.text_input("Đơn vị (VD: Điểm, Lần)", value="Điểm")

                if st.form_submit_button("Lưu Mục Tiêu", type="primary"):
                    if g_text:
                        new_goal = {
                            "id": int(time.time()), "text": g_text, "status": "Chưa bắt đầu",
                            "deadline": format_date_vn(g_date),
                            "kpi": { "baseline": g_base, "current": g_base, "target": g_target, "unit": g_unit, "history": [{"date": format_date_vn(datetime.now()), "value": g_base}] }
                        }
                        client['details']['goals'].append(new_goal)
                        st.rerun()

        for goal in client['details'].get('goals', []):
            with st.container(border=True):
                g_head1, g_head2 = st.columns([4, 1])

                # Checkbox đánh dấu hoàn thành
                is_done = goal['status'] == "Hoàn thành"
                new_done = g_head1.checkbox(f"**{goal['text']}**", value=is_done, key=f"chk_{goal['id']}")
                if new_done != is_done:
                    goal['status'] = "Hoàn thành" if new_done else "Đang tiến hành"
                    if new_done:
                        goal['kpi']['current'] = goal['kpi']['target']
                        goal['kpi']['history'].append({"date": format_date_vn(datetime.now()), "value": goal['kpi']['target']})
                    st.rerun()

                # Hiển thị cảnh báo thời gian
                warning = get_goal_warning(goal['deadline'], goal['status'])
                if warning:
                    g_head1.markdown(f"<span class='badge {warning['bg']} {warning['color']}'>Hạn: {goal['deadline']} ({warning['text']})</span>", unsafe_allow_html=True)
                else:
                    g_head1.caption(f"Hạn: {goal['deadline']}")

                # Nút xóa
                if g_head2.button(":material/delete:", key=f"del_g_{goal['id']}"):
                    client['details']['goals'] = [g for g in client['details']['goals'] if g['id'] != goal['id']]
                    st.rerun()

                # Giao diện KPI
                kpi = goal['kpi']
                st.markdown(f"<div style='background:#f8fafc;padding:10px;border-radius:8px;display:flex;justify-content:space-between;align-items:center'>"
                            f"<div><small>Gốc</small><br/><b>{kpi['baseline']}</b></div>"
                            f"<div>➡️</div>"
                            f"<div style='color:#2563eb'><small>Hiện tại</small><br/><b style='font-size:1.2rem'>{kpi['current']}</b></div>"
                            f"<div>➡️</div>"
                            f"<div style='color:#16a34a'><small>Đích</small><br/><b>{kpi['target']} {kpi['unit']}</b></div>"
                            f"</div>", unsafe_allow_html=True)

                # Popover cập nhật KPI Inline
                with st.popover("Cập nhật Giai đoạn (KPI)", use_container_width=True):
                    up_date = st.date_input("Ngày chấm điểm", key=f"upd_d_{goal['id']}")
                    up_val = st.number_input("Chỉ số mới", value=float(kpi['current']), key=f"upd_v_{goal['id']}")
                    if st.button("Lưu thay đổi", type="primary", key=f"save_kpi_{goal['id']}", use_container_width=True):
                        d_str = format_date_vn(up_date)
                        hist = kpi['history']
                        # Tìm và ghi đè nếu cùng ngày, ngược lại thêm mới
                        idx = next((i for i, h in enumerate(hist) if h['date'] == d_str), -1)
                        if idx >= 0: hist[idx]['value'] = up_val
                        else: hist.append({"date": d_str, "value": up_val})
                        # Sắp xếp lịch sử
                        hist.sort(key=lambda x: parse_date_vn(x['date']))
                        kpi['current'] = up_val
                        # Đánh giá hoàn thành
                        is_reached = (kpi['baseline'] < kpi['target'] and up_val >= kpi['target']) or (kpi['baseline'] > kpi['target'] and up_val <= kpi['target'])
                        goal['status'] = "Hoàn thành" if is_reached else "Đang tiến hành"
                        client['details']['timeline'].insert(0, {"date": format_date_vn(datetime.now()), "event": f"Cập nhật KPI: {goal['text']} -> {up_val}"})
                        st.rerun()

    # TAB 4: REFERRALS
    with tabs[3]:
        st.subheader("Điều phối Nguồn lực Hỗ trợ")

        with st.expander(":material/add_circle: Thêm kết nối mới"):
            with st.form("ref_form"):
                r1, r2 = st.columns(2)
                r_org = r1.text_input("Tên tổ chức / Đối tác")
                r_srv = r1.text_input("Dịch vụ cung cấp")
                r_stt = r2.selectbox("Trạng thái", ["Đã gửi giấy giới thiệu", "Chờ phản hồi", "Đã kết nối", "Đang điều trị"])
                if st.form_submit_button("Lưu Kết Nối", type="primary"):
                    if r_org:
                        client['details']['referrals'].append({"org": r_org, "service": r_srv, "status": r_stt, "date": format_date_vn(datetime.now())})
                        st.rerun()

        for ref in client['details'].get('referrals', []):
            st.info(f"🏢 **{ref['org']}** - {ref['service']}\n\n*Trạng thái: {ref['status']} | Cập nhật: {ref['date']}*")

    # TAB 5: EVALUATION
    with tabs[4]:
        eval_col1, eval_col2 = st.columns([3, 1])
        eval_col1.subheader("Biểu đồ Lượng giá Tiến trình")

        with eval_col2:
            if client['status'] != "Đã đóng ca":
                if st.button("✅ Lượng giá & Đóng ca", type="primary", use_container_width=True):
                    close_case_dialog(client['id'])
            else:
                if st.button("🔄 Mở lại can thiệp", use_container_width=True):
                    reopen_case_dialog(client['id'])

        # Vẽ Line Chart bằng Plotly
        has_chart = False
        for goal in client['details'].get('goals', []):
            kpi = goal.get('kpi')
            if kpi and kpi.get('history') and len(kpi['history']) > 0:
                has_chart = True
                hist = kpi['history']
                dates = [h['date'] for h in hist]
                values = [h['value'] for h in hist]

                # Tạo biểu đồ Plotly
                fig = go.Figure()
                # Line xanh biểu diễn thực tế
                fig.add_trace(go.Scatter(x=dates, y=values, mode='lines+markers', name='Tiến độ thực tế', line=dict(color='#3b82f6', width=3), marker=dict(size=8, color='#ffffff', line=dict(color='#3b82f6', width=2))))
                # Line ngang màu xanh lá biểu diễn đích
                fig.add_trace(go.Scatter(x=[dates[0], dates[-1]], y=[kpi['target'], kpi['target']], mode='lines', name='Đích (Target)', line=dict(color='#10b981', width=2, dash='dash')))

                fig.update_layout(
                    title=f"🎯 {goal['text']}",
                    xaxis_title="Thời gian", yaxis_title=f"Chỉ số ({kpi['unit']})",
                    height=300, margin=dict(l=20, r=20, t=40, b=20),
                    plot_bgcolor='white', paper_bgcolor='white',
                    xaxis=dict(showgrid=True, gridcolor='#f1f5f9'),
                    yaxis=dict(showgrid=True, gridcolor='#f1f5f9')
                )

                with st.container(border=True):
                    st.plotly_chart(fig, use_container_width=True)
                    st.caption(f"**Chỉ số hiện tại:** {kpi['current']} {kpi['unit']} | **Đích:** {kpi['target']} {kpi['unit']}")

        if not has_chart:
            st.write("Chưa có đủ dữ liệu KPI để vẽ biểu đồ.")

        st.divider()
        st.subheader("Nhật ký Hoạt động Tổng hợp")
        for item in client['details'].get('timeline', []):
            st.markdown(f"**{item['date']}**: {item['event']}")

# ==========================================
# 6. APP ROUTER
# ==========================================
if st.session_state.page == "Dashboard": render_dashboard()
elif st.session_state.page == "Clients": render_client_list()
elif st.session_state.page == "Intake": render_intake()
elif st.session_state.page == "Detail": render_client_detail()
else: render_dashboard()