# -*- coding: utf-8 -*-
"""SmartCase VN Toàn Diện

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PSdcPvCUIwWfTPIFbDM-6plvqmaUfbOr
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime, timedelta
import json
import requests
import time
import base64

# ==========================================
# 1. CẤU HÌNH TRANG & GIAO DIỆN
# ==========================================
st.set_page_config(page_title="SmartCase VN - Quản lý Ca AI", page_icon="🛡️", layout="wide")

# Custom CSS để giao diện trông hiện đại và chuyên nghiệp
st.markdown("""
    <style>
    .main { background-color: #f8fafc; }
    .stButton>button { border-radius: 8px; font-weight: bold; }
    .stMetric { background-color: white; padding: 15px; border-radius: 12px; border: 1px solid #e2e8f0; }
    .status-badge { padding: 4px 12px; border-radius: 99px; font-size: 12px; font-weight: bold; }
    .urgent { background-color: #fee2e2; color: #b91c1c; }
    .stable { background-color: #dcfce7; color: #15803d; }
    </style>
    """, unsafe_allow_html=True)

# ==========================================
# 2. KHỞI TẠO DỮ LIỆU (SESSION STATE)
# ==========================================
if 'clients' not in st.session_state:
    # Dữ liệu mẫu ban đầu
    st.session_state.clients = [
        {
            "id": "TE-001", "alias": "L.T.H", "age": 16, "category": "Bạo lực gia đình",
            "status": "Đang can thiệp", "riskLevel": "Khẩn cấp", "avatar": None,
            "address": "Quận 4, TP.HCM", "phone": "090xxxxxxx",
            "details": {
                "family": "Sống với bà ngoại (70 tuổi). Dượng ruột bạo hành.",
                "history": "Từng nhập viện do chấn thương phần mềm năm 2025.",
                "swot": {
                    "S": ["Rất thương bà ngoại", "Năng khiếu vẽ"],
                    "W": ["Tâm lý lo âu", "Kỹ năng đối phó kém"],
                    "O": ["Lớp học nghề miễn phí"],
                    "T": ["Dượng ruột đe dọa"]
                },
                "goals": [
                    {
                        "id": 1, "text": "Kiểm soát hoảng loạn tâm lý", "status": "Đang tiến hành",
                        "deadline": (datetime.now() + timedelta(days=10)).strftime("%d/%m/%Y"),
                        "kpi": {
                            "baseline": 8, "current": 3, "target": 1, "unit": "Cơn/Tuần",
                            "history": [
                                {"date": "01/04/2026", "value": 8},
                                {"date": "05/04/2026", "value": 5},
                                {"date": "10/04/2026", "value": 7}, # Tái phát
                                {"date": "15/04/2026", "value": 3}
                            ]
                        }
                    }
                ],
                "referrals": [{"org": "Hội LHPN Q4", "service": "Hỗ trợ pháp lý", "status": "Đã kết nối", "date": "10/04/2026"}],
                "timeline": [{"date": "15/04/2026", "event": "Lượng giá: Thân chủ tiến bộ."}]
            }
        }
    ]

# ==========================================
# 3. CÁC HÀM HỖ TRỢ (API, LOGIC)
# ==========================================
def call_gemini_api(prompt):
    api_key = "" # API Key sẽ được môi trường cung cấp
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key={api_key}"
    headers = {'Content-Type': 'application/json'}
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"responseMimeType": "application/json"}
    }

    for delay in [1, 2, 4]:
        try:
            response = requests.post(url, headers=headers, json=payload)
            if response.status_code == 200:
                result = response.json()
                return result['candidates'][0]['content']['parts'][0]['text']
        except:
            time.sleep(delay)
    return None

def get_base64_image(file):
    return f"data:image/png;base64,{base64.b64encode(file.getvalue()).decode()}"

# ==========================================
# 4. SIDEBAR NAVIGATION
# ==========================================
with st.sidebar:
    st.title("🛡️ SmartCase VN")
    st.caption("Hệ thống Quản lý Ca AI Toàn diện")
    st.divider()

    if 'page' not in st.session_state:
        st.session_state.page = "Dashboard"

    page = st.radio("Menu chính", ["📊 Tổng quan", "👥 Hồ sơ Thân chủ", "📝 Tiếp nhận mới"])
    st.divider()
    st.info("**Nhân viên:** SW-2026")

# ==========================================
# 5. MÀN HÌNH CHÍNH
# ==========================================

# --- TAB: DASHBOARD ---
if page == "📊 Tổng quan":
    st.header("Bảng Điều Khiển Hệ Thống")

    col1, col2, col3 = st.columns(3)
    active_count = len([c for c in st.session_state.clients if c['status'] != 'Đã đóng ca'])
    urgent_count = len([c for c in st.session_state.clients if c['riskLevel'] == 'Khẩn cấp' and c['status'] != 'Đã đóng ca'])

    col1.metric("Đang quản lý", active_count)
    col2.metric("Báo động Khẩn cấp", urgent_count)
    col3.metric("Lịch làm việc hôm nay", "5 ca")

    st.subheader("🔔 Chuông báo: Mục tiêu cần cập nhật KPI")
    warnings_found = False
    for client in st.session_state.clients:
        for goal in client['details'].get('goals', []):
            d_date = datetime.strptime(goal['deadline'], "%d/%m/%Y")
            if (d_date - datetime.now()).days <= 7 and goal['status'] != 'Hoàn thành':
                warnings_found = True
                with st.warning(f"**{client['id']} - {client['alias']}**: Mục tiêu '{goal['text']}' sắp hết hạn ({goal['deadline']})"):
                    if st.button(f"Cập nhật {client['id']}", key=f"warn_{goal['id']}"):
                        st.session_state.selected_client_id = client['id']
                        st.session_state.page_view = "detail"
                        st.rerun()
    if not warnings_found:
        st.success("Tất cả mục tiêu đều đang trong thời hạn an toàn.")

# --- TAB: CLIENT LIST ---
elif page == "👥 Hồ sơ Thân chủ":
    st.header("Danh Sách Hồ Sơ Quản Lý")

    filter_col1, filter_col2 = st.columns([2, 1])
    with filter_col1:
        mode = st.segmented_control("Phân loại hồ sơ", ["Đang can thiệp", "Đã đóng ca"], default="Đang can thiệp")

    filtered_clients = [c for c in st.session_state.clients if (c['status'] == "Đã đóng ca" if mode == "Đã đóng ca" else c['status'] != "Đã đóng ca")]

    if not filtered_clients:
        st.write("Không có hồ sơ nào trong danh mục này.")
    else:
        for client in filtered_clients:
            with st.container(border=True):
                c_col1, c_col2, c_col3, c_col4 = st.columns([1, 4, 2, 2])
                with c_col1:
                    if client['avatar']:
                        st.image(client['avatar'], width=60)
                    else:
                        st.write("👤")
                with c_col2:
                    st.write(f"**{client['id']} - {client['alias']}**")
                    st.caption(client['category'])
                with c_col3:
                    st.write(f"Mức rủi ro: {client['riskLevel']}")
                with c_col4:
                    if st.button("Xem & Can thiệp", key=f"btn_{client['id']}", use_container_width=True):
                        st.session_state.selected_client = client
                        st.session_state.page = "ClientDetail"
                        st.rerun()

# --- TAB: INTAKE (TIẾP NHẬN MỚI) ---
elif page == "📝 Tiếp nhận mới":
    st.header("Phiếu Tiếp Nhận & Phân Tích SWOT")

    with st.expander("✨ Trợ lý AI Phân tích Báo cáo", expanded=True):
        uploaded_file = st.file_uploader("Tải lên file báo cáo điền dã (.txt, .docx)", type=["txt", "docx"])
        if uploaded_file:
            with st.spinner("AI đang đọc và phân tích SWOT..."):
                time.sleep(2) # Giả lập xử lý
                st.success("Đã trích xuất dữ liệu thành công vào Form bên dưới!")

    with st.form("intake_form"):
        st.subheader("A. Thông Tin Cơ Bản")
        i_col1, i_col2 = st.columns(2)
        new_avatar = i_col1.file_uploader("Tải ảnh thẻ thân chủ", type=["jpg", "png"])
        new_alias = i_col1.text_input("Bí danh (Bảo mật) *")
        new_age = i_col2.number_input("Độ tuổi", min_value=0, max_value=120)
        new_category = i_col2.text_input("Nhóm đối tượng")
        new_family = st.text_area("Cấu trúc gia đình & Hoàn cảnh sống")

        st.subheader("B. Phân Tích SWOT")
        swot_col1, swot_col2 = st.columns(2)
        new_s = swot_col1.text_area("S - Điểm mạnh (Mỗi ý 1 dòng)")
        new_w = swot_col1.text_area("W - Điểm yếu (Mỗi ý 1 dòng)")
        new_o = swot_col2.text_area("O - Cơ hội bên ngoài")
        new_t = swot_col2.text_area("T - Thách thức rủi ro")

        if st.form_submit_button("💾 Lưu Hồ Sơ Mới"):
            if not new_alias:
                st.error("Vui lòng nhập bí danh.")
            else:
                avatar_data = get_base64_image(new_avatar) if new_avatar else None
                new_id = f"KH-{datetime.now().strftime('%M%S')}"
                st.session_state.clients.insert(0, {
                    "id": new_id, "alias": new_alias, "age": new_age, "category": new_category,
                    "status": "Tiếp nhận mới", "riskLevel": "Chưa đánh giá", "avatar": avatar_data,
                    "details": {
                        "family": new_family, "history": "",
                        "swot": {"S": new_s.split('\n'), "W": new_w.split('\n'), "O": new_o.split('\n'), "T": new_t.split('\n')},
                        "goals": [], "referrals": [], "timeline": [{"date": datetime.now().strftime("%d/%m/%Y"), "event": "Khởi tạo hồ sơ."}]
                    }
                })
                st.success(f"Đã tạo hồ sơ {new_id}")
                time.sleep(1)
                st.rerun()

# --- ROUTE: CLIENT DETAIL ---
elif page == "ClientDetail":
    client = st.session_state.selected_client

    # Header Area
    h_col1, h_col2, h_col3 = st.columns([1, 5, 2])
    with h_col1:
        if st.button("⬅️ Trở về"):
            st.session_state.page = "👥 Hồ sơ Thân chủ"
            st.rerun()
    with h_col2:
        st.title(f"Hồ sơ: {client['id']} ({client['alias']})")
    with h_col3:
        if st.button("🗑️ Xóa hồ sơ", type="primary"):
            st.session_state.clients = [c for c in st.session_state.clients if c['id'] != client['id']]
            st.session_state.page = "👥 Hồ sơ Thân chủ"
            st.rerun()

    tab1, tab2, tab3, tab4, tab5 = st.tabs(["1. Thông tin", "2. SWOT", "3. Kế hoạch KPI", "4. Nguồn lực", "5. Lượng giá"])

    with tab1:
        t1_col1, t1_col2 = st.columns([1, 3])
        with t1_col1:
            if client['avatar']: st.image(client['avatar'])
            else: st.info("Chưa có ảnh")
        with t1_col2:
            st.write(f"**Độ tuổi:** {client['age']}")
            st.write(f"**Nhóm vấn đề:** {client['category']}")
            st.write(f"**Hoàn cảnh:** {client['details']['family']}")
            if st.button("📝 Chỉnh sửa thông tin"):
                st.info("Tính năng đang mở rộng...")

    with tab2:
        st.subheader("Phân tích SWOT")
        s_col1, s_col2 = st.columns(2)
        s_col1.success(f"**S - Strengths:** \n\n " + "\n- ".join(client['details']['swot']['S']))
        s_col1.warning(f"**W - Weaknesses:** \n\n " + "\n- ".join(client['details']['swot']['W']))
        s_col2.info(f"**O - Opportunities:** \n\n " + "\n- ".join(client['details']['swot']['O']))
        s_col2.error(f"**T - Threats:** \n\n " + "\n- ".join(client['details']['swot']['T']))

    with tab3:
        st.subheader("Mục tiêu can thiệp")
        for i, goal in enumerate(client['details']['goals']):
            with st.expander(f"🎯 {goal['text']} - Hạn: {goal['deadline']}", expanded=True):
                g_col1, g_col2 = st.columns([3, 1])
                g_col1.write(f"Tiến độ: **{goal['kpi']['current']}/{goal['kpi']['target']}** {goal['kpi']['unit']}")

                with g_col2:
                    new_val = st.number_input("Cập nhật chỉ số", value=float(goal['kpi']['current']), key=f"input_{goal['id']}")
                    new_date = st.date_input("Ngày chấm điểm", value=datetime.now(), key=f"date_{goal['id']}")
                    if st.button("Lưu giai đoạn", key=f"save_{goal['id']}"):
                        goal['kpi']['current'] = new_val
                        goal['kpi']['history'].append({"date": new_date.strftime("%d/%m/%Y"), "value": new_val})
                        # Sort history
                        goal['kpi']['history'].sort(key=lambda x: datetime.strptime(x['date'], "%d/%m/%Y"))
                        st.success("Đã cập nhật!")
                        st.rerun()

    with tab4:
        st.subheader("Nguồn lực hỗ trợ")
        for ref in client['details']['referrals']:
            st.write(f"✅ **{ref['org']}**: {ref['service']} ({ref['status']})")
        if st.button("+ Kết nối nguồn lực mới"):
            st.info("Form thêm nguồn lực...")

    with tab5:
        st.subheader("Biểu đồ Lượng giá Tiến trình")
        for goal in client['details']['goals']:
            if goal['kpi'].get('history'):
                history = goal['kpi']['history']
                dates = [h['date'] for h in history]
                values = [h['value'] for h in history]

                fig = go.Figure()
                # Line chính
                fig.add_trace(go.Scatter(x=dates, y=values, mode='lines+markers', name='Tiến độ thực tế', line=dict(color='#3b82f6', width=3)))
                # Đường Target
                fig.add_trace(go.Scatter(x=[dates[0], dates[-1]], y=[goal['kpi']['target'], goal['kpi']['target']],
                                         mode='lines', name='Mục tiêu', line=dict(color='#10b981', dash='dash')))

                fig.update_layout(title=f"Tiến trình: {goal['text']}", height=300, margin=dict(l=20, r=20, t=40, b=20))
                st.plotly_chart(fig, use_container_width=True)

        st.divider()
        if client['status'] != "Đã đóng ca":
            if st.button("🔒 Đóng hồ sơ (Kết thúc can thiệp)", type="primary"):
                client['status'] = "Đã đóng ca"
                st.rerun()
        else:
            if st.button("🔓 Mở lại hồ sơ can thiệp"):
                client['status'] = "Đang can thiệp"
                st.rerun()